# Generated by Django 4.2.9 on 2024-02-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='banner_h1',
            field=models.CharField(default='higher/top_text', max_length=50),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='banner_h3',
            field=models.CharField(default='lower_text', max_length=50),
        ),
    ]
