# Generated by Django 4.2.9 on 2024-02-01 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_companyprofile_banner_h1_companyprofile_banner_h3'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('item_img', models.ImageField(upload_to='item_img')),
                ('p1', models.TextField(blank=True, null=True)),
                ('p2', models.TextField(blank=True, null=True)),
                ('p3', models.TextField(blank=True, null=True)),
                ('p4', models.TextField(blank=True, null=True)),
                ('p5', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'application',
                'verbose_name_plural': 'applications',
                'db_table': 'application',
                'managed': True,
            },
        ),
    ]
