# Generated by Django 4.2.9 on 2024-02-02 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0005_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThanksEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=5000)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'thanks edit',
                'verbose_name_plural': 'thanks edits',
                'db_table': 'thanks edit',
                'managed': True,
            },
        ),
    ]
