# Generated by Django 4.2.9 on 2024-02-02 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0008_rename_text_cryptoinfo_wallet_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CryptoInfo',
        ),
    ]
