# Generated by Django 4.2.9 on 2024-02-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0009_delete_cryptoinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BnbInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(max_length=5000)),
                ('scan', models.ImageField(upload_to='crypto')),
                ('cryptologo', models.ImageField(upload_to='crypto')),
            ],
            options={
                'verbose_name': 'bnb',
                'verbose_name_plural': 'bnb',
                'db_table': 'bnb',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BtcInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(max_length=5000)),
                ('scan', models.ImageField(upload_to='crypto')),
                ('cryptologo', models.ImageField(upload_to='crypto')),
            ],
            options={
                'verbose_name': 'btc ',
                'verbose_name_plural': 'btc ',
                'db_table': 'btc ',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DogeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(max_length=5000)),
                ('scan', models.ImageField(upload_to='crypto')),
                ('cryptologo', models.ImageField(upload_to='crypto')),
            ],
            options={
                'verbose_name': 'doge',
                'verbose_name_plural': 'doge',
                'db_table': 'doge',
                'managed': True,
            },
        ),
    ]
